version: '2.0'

services:
  ad:
    build:
      context: .
      dockerfile: ad-Dockerfile
    ports:
      - "8080:8080"
    volumes:
      #      maven本地仓库或者docker虚拟卷
      - E:/jetbrains/maven/repository:/mvn-repo
      #      src目录
      - .:/mvn-src
    depends_on:
      - ad_mysql

  ad_mysql:
    build:
      context: .
      dockerfile: Mysql-Dockfile
    ports:
      - "6666:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123123
      MYSQL_DATABASE: ad

