#custom
custom:
  mysql:
    address: ad_mysql
    password: root
    port: 3306
    database: ad
    config: autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&useAffectedRows=true

