#custom
custom:
  mysql:
    address: localhost
    password: 123123
    port: 3306
    database: ad
    username: root
    config: autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=utf8&useAffectedRows=true

#用于显示绑定的参数具体值

logging:
  level:
    org:
      hibernate:
        #        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder: trace