#custom
custom:
  mysql:
    address: ad_mysql
    password: 123123
    port: 6666
    database: ad
    config: autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&useAffectedRows=true

